create table public.guestbook_entries (
  id bigint generated by default as identity primary key,
  name varchar(20) not null,
  message varchar(300) not null,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create index idx_guestbook_entries_created_at
  on public.guestbook_entries (created_at desc, id desc);

create table public.attendance_survey_responses (
  id bigint generated by default as identity primary key,
  attendance text not null check (attendance in ('attending', 'not-attending')),
  name varchar(20) not null,
  phone varchar(11) not null unique,
  meal_plan text not null check (meal_plan in ('yes', 'no', 'undecided', 'not-applicable')),
  guest_count integer not null check (guest_count between 0 and 10),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_attendance_survey_updated_at
  on public.attendance_survey_responses (updated_at desc, id desc);

create table public.bus_survey_responses (
  id bigint generated by default as identity primary key,
  name varchar(20) not null,
  phone varchar(11) not null unique,
  outbound_count integer not null check (outbound_count between 1 and 10),
  note varchar(200) not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_bus_survey_updated_at
  on public.bus_survey_responses (updated_at desc, id desc);

alter table public.guestbook_entries enable row level security;
alter table public.attendance_survey_responses enable row level security;
alter table public.bus_survey_responses enable row level security;

revoke all on table public.guestbook_entries from anon, authenticated;
revoke all on table public.attendance_survey_responses from anon, authenticated;
revoke all on table public.bus_survey_responses from anon, authenticated;

grant usage on schema public to service_role;
grant all on table public.guestbook_entries to service_role;
grant all on table public.attendance_survey_responses to service_role;
grant all on table public.bus_survey_responses to service_role;
grant usage, select on all sequences in schema public to service_role;
